export const genres = [
	{ label: 'Adventure', value: 'Adventure', colorScheme: 'red' },
	{ label: 'Action', value: 'Action', colorScheme: 'blue' },
	{ label: 'Biography', value: 'Biography', colorScheme: 'green' },
	{ label: 'Children', value: 'Children', colorScheme: 'yellow' },
	{ label: 'Comedy', value: 'Comedy', colorScheme: 'purple' },
	{ label: 'Crime', value: 'Crime', colorScheme: 'orange' },
	{ label: 'Drama', value: 'Drama', colorScheme: 'cyan' },
	{ label: 'Fantasy', value: 'Fantasy', colorScheme: 'teal' },
	{ label: 'History', value: 'History', colorScheme: 'pink' },
	{ label: 'Horror', value: 'Horror', colorScheme: 'gray' },
	{ label: 'Mystery', value: 'Mystery', colorScheme: 'cyan' },
	{ label: 'Romance', value: 'Romance', colorScheme: 'teal' },
	{ label: 'Science Fiction', value: 'Science Fiction', colorScheme: 'purple' },
	{ label: 'Thriller', value: 'Thriller', colorScheme: 'red' },
	{ label: 'Western', value: 'Western', colorScheme: 'orange' },
	{ label: 'Non-Fiction', value: 'Non-Fiction', colorScheme: 'green' },
	{ label: 'Poetry', value: 'Poetry', colorScheme: 'yellow' },
	{ label: 'Self-Help', value: 'Self-Help', colorScheme: 'pink' },
	{ label: 'Travel', value: 'Travel', colorScheme: 'gray' },
	{ label: 'Cookbooks', value: 'Cookbooks', colorScheme: 'cyan' },
	{ label: 'Health', value: 'Health', colorScheme: 'blue' },
];
