name: Build and Deploy
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

permissions:
    contents: read
    pull-requests: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Test
              run: npm test

            - name: Test Report
              uses: dorny/test-reporter@v1
              with:
                  name: Test Report
                  path: src/test/*.xml
                  reporter: jest-junit
